### ISSUE TITLE
Update grad student graduating years

### ISSUE THREAD

**Issue by amshin98** [cal-poly-slo-cs-tutoring/Website#23]
James, Joey, and Kevin are all Class of 2021 now. Already have Ryan as 2021, confirmed with him.

**Comment by gage117** [comment]
I would like to take care of this. Do I have to fork it before cloning and making a new branch or can I just clone without forking?

**Comment by amshin98** [comment]
Go ahead and do whatever you're comfortable with and then submit a pull request. Thanks for the help!

**Comment by gage117** [comment]
Pull request made

**Comment by amshin98** [comment]
Closed in 49a96c4ac26030ecb2279e1a47add4f347b849b5
