### ISSUE TITLE
Make the release process automated

### ISSUE THREAD

**Issue by nvaa36** [cal-poly-slo-cs-tutoring/Website#3]
The root for the website is /var/www/tutoring/ so that's where everything is being served from. There is currently no automation, so if you make changes to the repo you have to manually copy them to /tutoring to have the website actually display them. Might be a bit of work, but will eventually make it easier.

**Comment by amshin98** [comment]
Using DeployHQ, deployments are triggered on pushes to master. Only the src directory is copied to the website root on the box, as nothing else really needs to be. We're using the free tier so we get 10 deployments every 24 hours.
